#
#
#spring:
#  application:
#    name: "company"
#  profiles:
#    active: "service"
#  config:
#    import: "optional:configserver:http://13.232.2.228:8888"



spring:
  application:
    name: "company"
  profiles:
    active: "service"
  config:
    import: "optional:configserver:http://18.116.208.129:8888"
