#server:
# port: 8010
#eureka:
#     client:
#      register-with-eureka:  true
#spring:
# application:
#   name: COMPANY-SERVICE
# datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/buildlive_company
#    username: root
#    password: '@77SUDHA'
# jpa:
#    hibernate:
#        ddl-auto: update
#    database: mysql
#    database-platform: org.hibernate.dialect.MySQLDialect
#

spring:
  application:
    name: "company"
  profiles:
    active: "service"
  config:
    import: "optional:configserver:http://13.127.132.74:8888"
#  zipkin:
#    base:
#      url: http://127.0.0.1:9411/
#  sleuth:
#    sampler:
#      probability: 1.0
#
#
#
#management:
#  health:
#    circuitbreakers:
#      enabled: true
#    endpoints:
#      web:
#        exposure:
#          include: health
#    endpoint:
#      health:
#        show-details: always
#
#resilience4j:
#  circuitbreaker:
#    instances:
#      company-service:
#        registerHealthIndicator: true
#        eventConsumerBufferSize: 10
#        failureRateThreshold: 50
#        minimumNumberOfCalls: 5
#        automaticTransitionFromOpenToHalfOpenEnabled: true
#        waitDurationInOpenState: 5s
#        permittedNumberOfCallsInHalfOpenState: 3
#        slidingWindowSize: 10
#        slidingWindowType: COUNT_BASED