#server:
# port: 8010
#eureka:
#     client:
#      register-with-eureka:  true
#spring:
# application:
#   name: COMPANY-SERVICE
# datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/buildlive_company
#    username: root
#    password: '@77SUDHA'
# jpa:
#    hibernate:
#        ddl-auto: update
#    database: mysql
#    database-platform: org.hibernate.dialect.MySQLDialect
#

spring:
  application:
    name: "company"
  profiles:
    active: "service"
  config:
    import: "optional:configserver:http://localhost:8888"
  zipkin:
    base:
      url: http://127.0.0.1:9411/
  sleuth:
    sampler:
      probability: 1.0